apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: app

resources:
- volumes/jenkins-pv.yaml
- volumes/jenkins-pvc.yaml
- svc/jenkins-service.yaml
- deployment/jenkins-deployment.yaml
